### ISSUE TITLE
Написать техническое задание

### ISSUE THREAD

**Issue by wldmr-key** [TvojaMamaLama/lama-pasture#1]
Вот эта штучка, где я пишу, называется issue или задача. Всю работу над проектом целесообразно разбивать на задачи. Меньшую часть из них пишу я. Большую ты должен ставить себе сам.

Вот первая - написать техническое задание по ГОСТ. Перед тем как сделать это, попробуй описать в 5-7 предложениях, что ты собираешься сделать и записать их в комментарий к этой задаче

**Comment by toshaklg** [comment]
Давай Никит

**Comment by toshaklg** [comment]
Я верю в тебя

**Comment by TvojaMamaLama** [comment]
ТЗ ГОТОВО

**Comment by toshaklg** [comment]
![chrome_2wjXIkAB2N](https://user-images.githubusercontent.com/43007372/65938442-a38a7e80-e42b-11e9-9d6c-cf4d6c867320.png)
